/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package apresentacao;

/**
 *
 * @author powji
 */
public class frmConteudo3 extends javax.swing.JDialog {

    /**
     * Creates new form frmConteuro
     */
    public frmConteudo3(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        btnContinuar = new javax.swing.JButton();
        lblPerseverance = new javax.swing.JLabel();
        lblCuriosity = new javax.swing.JLabel();
        lblImagemPerseverance = new javax.swing.JLabel();
        lblimagemCuriosity = new javax.swing.JLabel();
        lblFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1525, 790));
        setResizable(false);
        getContentPane().setLayout(null);

        btnContinuar.setBackground(new java.awt.Color(74, 43, 23));
        btnContinuar.setFont(new java.awt.Font("Eras Bold ITC", 0, 18)); // NOI18N
        btnContinuar.setForeground(new java.awt.Color(164, 127, 85));
        btnContinuar.setText("Continuar");
        btnContinuar.setBorder(null);
        btnContinuar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnContinuarActionPerformed(evt);
            }
        });
        getContentPane().add(btnContinuar);
        btnContinuar.setBounds(1275, 633, 180, 70);

        lblPerseverance.setFont(new java.awt.Font("Eras Bold ITC", 0, 36)); // NOI18N
        lblPerseverance.setForeground(new java.awt.Color(74, 43, 23));
        lblPerseverance.setText("Perseverance em exposição");
        getContentPane().add(lblPerseverance);
        lblPerseverance.setBounds(920, 420, 510, 50);

        lblCuriosity.setFont(new java.awt.Font("Eras Bold ITC", 0, 36)); // NOI18N
        lblCuriosity.setForeground(new java.awt.Color(74, 43, 23));
        lblCuriosity.setText("Curiosity em exposição");
        getContentPane().add(lblCuriosity);
        lblCuriosity.setBounds(200, 270, 430, 50);

        lblImagemPerseverance.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/obras2.jpg"))); // NOI18N
        lblImagemPerseverance.setText("jLabel1");
        getContentPane().add(lblImagemPerseverance);
        lblImagemPerseverance.setBounds(890, 100, 560, 320);

        lblimagemCuriosity.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/obras1.jpg"))); // NOI18N
        getContentPane().add(lblimagemCuriosity);
        lblimagemCuriosity.setBounds(70, 330, 670, 380);

        lblFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/FundoGeral.jpg"))); // NOI18N
        lblFundo.setAlignmentY(0.0F);
        getContentPane().add(lblFundo);
        lblFundo.setBounds(0, 0, 1525, 790);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContinuarActionPerformed
            frmPergunta4 frmP4 = new frmPergunta4(null, true);
            this.setVisible(false);
            frmP4.setVisible(true);  
    }//GEN-LAST:event_btnContinuarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmConteudo1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmConteudo1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmConteudo1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmConteudo1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                frmConteudo1 dialog = new frmConteudo1(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnContinuar;
    private javax.swing.JLabel lblCuriosity;
    private javax.swing.JLabel lblFundo;
    private javax.swing.JLabel lblImagemPerseverance;
    private javax.swing.JLabel lblPerseverance;
    private javax.swing.JLabel lblimagemCuriosity;
    // End of variables declaration//GEN-END:variables
}
