/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package apresentacao;


import java.util.TimerTask;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import modelo.*;
/**
 *
 * @author User
 */
public class frmFinal extends javax.swing.JDialog
{

    /**
     * Creates new form frmFinal
     */
    public frmFinal(java.awt.Frame parent, boolean modal)
    {
        super(parent, modal);
        initComponents();
        lblNome.setText(Estaticos.NOME);
        lblTotalRespo.setText(Estaticos.TEXTO);
        if(Estaticos.SOMAACERTOS >= 3){
            lblSituacao.setText("Parabens!!");
            lblAcertos.setText(Estaticos.ACERTOS);
            imgParabens.setVisible(true);
            imgOutro.setVisible(false);
        }else
        {
            lblSituacao.setText("Que pena!");
            lblAcertos.setText(Estaticos.ACERTOS);
            imgParabens.setVisible(false);
            imgOutro.setVisible(true);
        }
        
        
        new java.util.Timer().schedule(new TimerTask() {
            @Override
            public void run() {
                //executar ação aqui
            btnFinalizar.doClick();
            }
        }, 7000);

        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        btnFinalizar = new javax.swing.JButton();
        lblTotalRespo = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        lblAcertos = new javax.swing.JLabel();
        lblSituacao = new javax.swing.JLabel();
        imgParabens = new javax.swing.JLabel();
        imgOutro = new javax.swing.JLabel();
        btnMostrarDados = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1535, 850));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnFinalizar.setText("finalizar");
        btnFinalizar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnFinalizarActionPerformed(evt);
            }
        });
        getContentPane().add(btnFinalizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 410, 121, 39));
        getContentPane().add(lblTotalRespo, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 917, 449, 20));

        lblNome.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        lblNome.setText("seu nome");
        getContentPane().add(lblNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 170, 50));

        lblAcertos.setText("total de acerto");
        getContentPane().add(lblAcertos, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 156, -1));

        lblSituacao.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        lblSituacao.setText("Parabens!!");
        getContentPane().add(lblSituacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 40, 260, 40));

        imgParabens.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Documents\\NetBeansProjects\\Aps\\src\\img\\img1.gif")); // NOI18N
        imgParabens.setText("jLabel1");
        imgParabens.setToolTipText("");
        getContentPane().add(imgParabens, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 200, 480, 360));

        imgOutro.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Documents\\NetBeansProjects\\Aps\\src\\img\\img2.gif")); // NOI18N
        imgOutro.setText("jLabel1");
        getContentPane().add(imgOutro, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 190, 540, 370));

        btnMostrarDados.setText("respostas ");
        btnMostrarDados.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnMostrarDadosActionPerformed(evt);
            }
        });
        getContentPane().add(btnMostrarDados, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 420, 132, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFinalizarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnFinalizarActionPerformed
    {//GEN-HEADEREND:event_btnFinalizarActionPerformed
        frmInicial frmI = new frmInicial(null, true);
        this.setVisible(false);
        frmI.setVisible(true);
    }//GEN-LAST:event_btnFinalizarActionPerformed

    private void btnMostrarDadosActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnMostrarDadosActionPerformed
    {//GEN-HEADEREND:event_btnMostrarDadosActionPerformed

    // Cria uma instância de StringBuilder para construir uma string 
        // StringBuilder é uma classe do pacote java.lang.
    StringBuilder sb = new StringBuilder(); 

    // Vai ate a lista de visitantes obtida pelo método estático getListaVisitantes()
    for (Visitantes visitante : Visitantes.getListaVisitantes()) 
    {
    // Adiciona a representação em string de cada visitante ao StringBuilder, seguida por uma nova linha
    sb.append(visitante.toString()).append("\n"); 
    }
    // Exibe uma caixa de diálogo com o conteúdo do StringBuilder, que contém as informações dos visitantes
    JOptionPane.showMessageDialog(null, sb); 

    }//GEN-LAST:event_btnMostrarDadosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(frmFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(frmFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(frmFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(frmFinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                frmFinal dialog = new frmFinal(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter()
                {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e)
                    {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFinalizar;
    private javax.swing.JButton btnMostrarDados;
    private javax.swing.JLabel imgOutro;
    private javax.swing.JLabel imgParabens;
    private javax.swing.JLabel lblAcertos;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblSituacao;
    private javax.swing.JLabel lblTotalRespo;
    // End of variables declaration//GEN-END:variables
}
